language: generic
services: docker

branches:
  only:
    - master

env:
  - BASE=alpine VERSION=15
  - BASE=alpine VERSION=16
  - BASE=alpine VERSION=17
  - BASE=alpine VERSION=latest
  - BASE=ruby VERSION=15
  - BASE=ruby VERSION=16
  - BASE=ruby VERSION=17
  - BASE=ruby VERSION=latest

script:
  - ./build.sh
