name: Build

on:
  schedule:
    - cron:  '0 0 15 * *'
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - base: alpine
           version: 15
         - base: alpine
           version: 16
         - base: alpine
           version: 17
         - base: alpine
           version: latest
         - base: ruby
           version: 15
         - base: ruby
           version: 16
         - base: ruby
           version: 17
         - base: ruby
           version: latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      env:
        BASE: ${{ matrix.base }}
        VERSION: ${{ matrix.version }}
      run: ./build.sh
