name: Main

on:
  schedule:
    - cron:  '0 0 15 * *'
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - base: alpine
           gem: chef --version ~>
           version: 15
           tag: alpine-15
         - base: alpine
           gem: chef --version ~>
           version: 16
           tag: alpine-16
         - base: alpine
           gem: knife --version ~>
           version: 17
           tag: alpine-17
         - base: alpine
           gem: knife
           version: ""
           tag: alpine-latest
         - base: ruby
           gem: chef --version ~>
           version: 15
           tag: ruby-15
         - base: ruby
           gem: chef --version ~>
           version: 16
           tag: ruby-16
         - base: ruby
           gem: knife --version ~>
           version: 17
           tag: ruby-17
         - base: ruby
           gem: knife --version ~>
           version: ""
           tag: latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.base }}/.
        push: true
        tags: johnbarney/knife:${{ matrix.tag }}
        build-args: VERSION="${{ matrix.version }}" GEM=${{ matrix.gem }}
